Dns c tests
ElrondNetwork/wasm-vm pull request #199
Opened 2020-11-20 11:33 UTC by dorin-iancu

DNS C tests + getExternalBalance fix + new myDebug function for debugging purposes (which is basically the equivalent of finish() with some printlns)

2020-11-20 12:03 UTC, andrei-marinica submitted a review, later dismissed

2020-11-23 11:15 UTC, sasurobert requested changes

2020-11-23 11:15 UTC, sasurobert commented on arwen/elrondapi/elrondei.go
> +	balance32Bytes := make([]byte, 32)
add a constant for 32 - there should already be some constants for it.

2020-11-23 11:15 UTC, sasurobert commented on arwen/elrondapi/elrondei.go
> +	//output := arwen.GetOutputContext(context)
delete commented code

2020-11-23 11:15 UTC, sasurobert commented on arwen/elrondapi/elrondei.go
> +	fmt.Println("Pointer:", pointer, " Length: ", length)
delete this debug function. we do not want to fill the nodes screen with these written data.

2020-11-23 11:15 UTC, sasurobert commented on arwen/elrondapi/elrondei.go
> +	balance32Bytes := make([]byte, 32)
add a constant for 32 - there should already be some constants for it.

2020-11-24 12:45 UTC, sasurobert approved these changes

2022-03-03 08:25 UTC, closed without merging