Elrondgo mandos exporter
ElrondNetwork/wasm-vm pull request #436
Opened 2021-10-19 11:21 UTC by andrei-diaconescu

2021-10-19 12:33 UTC, andrei-marinica requested changes

2021-10-19 12:33 UTC, andrei-marinica commented on arwenmandos/util.go
> +func CreateMultiTransferData(to []byte, esdtData []*mj.ESDTTxData, endpointName string, arguments [][]byte) []byte {
also move this entire file and the tests to mandos-go/util, other projects will also make use of it

2021-11-11 14:03 UTC, camilbancioiu requested changes

2021-11-11 14:03 UTC, camilbancioiu commented on mandos-go/elrondgo-exporter/elrondGoExporter.go
> +					if txIdRequieresBenchmark(step.TxIdent) && benchmarkTxPosIsNotSet(benchmarkTxPos) {
Minor typo: `Requires`

2021-11-11 14:03 UTC, camilbancioiu commented on mandos-go/elrondgo-exporter/elrondGoExporter.go
> +
Delete empty line.

2021-11-11 14:03 UTC, camilbancioiu commented on mandos-go/elrondgo-exporter/elrondGoExporter.go
> +	return accounts, deployedAccounts, txs, deployTxs, benchmarkTxPos, nil
Optional, but strongly recommended: create a `struct` called `ScenarioWithBenchmark` (or similarly named) which contains all these values as fields.

2021-11-11 14:05 UTC, camilbancioiu commented on mandos-go/elrondgo-exporter/elrondGoExporter.go
> +func convertMandosToTestAccount(mandosAcc *mj.Account) (*TestAccount, error) {
Consider renaming to `convertMandosAccountToTestAccount`.

2021-11-11 14:07 UTC, camilbancioiu commented on mandos-go/elrondgo-exporter/exportedTransaction.go
> +	tx.sndAddr = address
You probably wanted this:
```suggestion
	tx.sndAddr = make([]byte, len(address))
	tx.sndAddr = copy(tx.sndAddr, address)
```

2021-11-15 14:21 UTC, andrei-marinica approved these changes

2021-11-15 14:38 UTC, camilbancioiu approved these changes

2021-11-15 14:49 UTC, merged