v1_4_mBufferSetByteSlice
ElrondNetwork/wasm-vm pull request #475
Opened 2021-11-25 16:15 UTC by camilbancioiu

2021-11-25 16:19 UTC, sasurobert commented on arwen/elrondapi/manBufOps.go
> +	//TODO this loop should be faster than append() on slices, but needs benchmarking
Delete todo

2021-11-25 16:19 UTC, sasurobert commented on arwen/elrondapi/manBufOps.go
> +	imports, err = imports.Append("mBufferSetByteSlice", v1_4_mBufferSetByteSlice, C.v1_4_mBufferSetByteSlice)
Need flag. Backward compatibility

2021-11-25 16:19 UTC, sasurobert commented on arwen/elrondapi/manBufOps.go
> +	imports, err = imports.Append("mBufferSetByteSlice", v1_4_mBufferSetByteSlice, C.v1_4_mBufferSetByteSlice)
Should be created on if flag is active. It is a little bit more complicated.

2021-11-26 09:26 UTC, camilbancioiu commented on arwen/elrondapi/manBufOps.go
> +	//TODO this loop should be faster than append() on slices, but needs benchmarking
Deleted.

2021-11-26 12:08 UTC, camilbancioiu commented on arwen/elrondapi/elrondei.go
> +func v1_4_getESDTLocalRoles(context unsafe.Pointer, tokenIdHandle int32) int64 {
This API method is being reworked due to a required fix.

2021-11-26 12:10 UTC, camilbancioiu commented on arwen/elrondapi/elrondei.go
> +func v1_4_getESDTLocalRoles(context unsafe.Pointer, tokenIdHandle int32) int64 {
The code was expecting an incorrect type to be stored in the storage.

2021-11-26 12:13 UTC, sasurobert requested changes

2021-11-26 12:13 UTC, sasurobert commented on arwen/elrondapi/elrondei.go
> +	gasToUse := metering.GasSchedule().ElrondAPICost.StorageLoad
storageLoad ? that is a big cost. put something else here.

2021-11-26 12:13 UTC, sasurobert commented on arwen/elrondapi/elrondei.go
> +	gasToUse := metering.GasSchedule().ElrondAPICost.StorageLoad
Use getArgument cost.

2021-11-26 12:13 UTC, sasurobert commented on arwen/elrondapi/elrondei.go
> +
delete empty line

2021-11-26 12:13 UTC, sasurobert commented on arwen/elrondapi/elrondei.go
> +	for i := 0; i < tickerLen-1; i++ {
func isTickerValid(tickerName []byte) bool {
	if len(tickerName) < minLengthForTickerName || len(tickerName) > maxLengthForTickerName {
		return false
	}

	for _, ch := range tickerName {
		isBigCharacter := ch >= 'A' && ch <= 'Z'
		isNumber := ch >= '0' && ch <= '9'
		isReadable := isBigCharacter || isNumber
		if !isReadable {
			return false
		}
	}

	return true
}

2021-11-26 12:13 UTC, sasurobert commented on arwen/elrondapi/elrondei.go
> +	key := []byte("ELRONDroleesdt" + string(tokenID))
define the const for keyPrefix

2021-11-26 12:13 UTC, sasurobert commented on arwen/elrondapi/elrondei.go
> +	result := int64(0)
make a separate function out of lines 956-974 and you will be able to easily unit test

2021-11-26 12:19 UTC, camilbancioiu commented on arwen/contexts/runtime.go
> +	if !context.flagUseDifferentGasCostForReadingCachedStorage.IsSet() {
Done.

2021-11-26 14:42 UTC, sasurobert submitted a review, later dismissed

2021-11-26 15:38 UTC, sasurobert approved these changes

2021-11-26 15:39 UTC, alyn509 approved these changes

2021-11-26 15:39 UTC, andrei-marinica approved these changes

2021-11-26 15:39 UTC, merged