update account on set existing
ElrondNetwork/wasm-vm pull request #477
Opened 2021-11-26 15:01 UTC by catalinnnn

2021-11-29 09:28 UTC, andrei-marinica approved these changes

2021-11-29 17:19 UTC, andrei-diaconescu approved these changes

2022-03-03 09:52 UTC, merged

2022-03-03 09:53 UTC, andrei-marinica requested changes

2022-03-03 09:53 UTC, andrei-marinica commented on arwenmandos/execScenario.go
> +	existingAccount := ae.World.AcctMap.GetAccount(mandosAccount.Address.Value)
Duplicate code as in the method above. Merge them in one method and make the update check there.

2022-03-03 09:53 UTC, andrei-marinica commented on arwenmandos/execScenario.go
> +	for k, v := range worldAccount.Storage {
The part from here can be extracted to another method, if you want smaller methods.