Managed keccak256 ei
ElrondNetwork/wasm-vm pull request #478
Opened 2021-11-26 20:45 UTC by andrei-marinica

2021-11-27 10:47 UTC, camilbancioiu requested changes

2021-11-27 10:47 UTC, camilbancioiu commented on arwen/cryptoapi/cryptoei.go
> +	metering.UseGasAndAddTracedGas(keccak256Name, metering.GasSchedule().CryptoAPICost.SHA256)
```suggestion
	metering.UseGasAndAddTracedGas(sha256Name, metering.GasSchedule().CryptoAPICost.SHA256)
```

2021-11-27 10:51 UTC, camilbancioiu commented
The new managed API methods appear to consume just as much gas as the unmanaged ones, even if they should be much faster. We could create a new cost `ManagedCopyDataPerByte`, or simply `ManagedSHA256` and `ManagedKeccak256` with smaller values.

2021-11-27 11:29 UTC, andrei-marinica commented
> The new managed API methods appear to consume just as much gas as the unmanaged ones, even if they should be much faster. We could create a new cost `ManagedCopyDataPerByte`, or simply `ManagedSHA256` and `ManagedKeccak256` with smaller values.

Fully agree, but it's more important to just have this functionality for now, even if it could be made cheaper.

2021-11-29 07:38 UTC, sasurobert commented
> The new managed API methods appear to consume just as much gas as the unmanaged ones, even if they should be much faster. We could create a new cost `ManagedCopyDataPerByte`, or simply `ManagedSHA256` and `ManagedKeccak256` with smaller values.

There is no need for API costs in case of crypto the actual crypto computation consumes the most of the time.

2021-11-29 07:39 UTC, sasurobert approved these changes

2021-11-29 08:33 UTC, camilbancioiu approved these changes

2021-11-29 08:54 UTC, merged