closure for new async calls
ElrondNetwork/wasm-vm pull request #565
Opened 2022-05-27 07:07 UTC by matei-p

2022-06-03 16:07 UTC, andrei-marinica submitted a review, later dismissed

2022-06-14 10:35 UTC, sasurobert requested changes

2022-06-14 10:35 UTC, sasurobert commented on arwen/elrondapi/managedei.go
> +	host := arwen.GetVMHost(context)
gas use ?

2022-06-16 07:23 UTC, matei-p commented on arwen/elrondapi/managedei.go
> +	host := arwen.GetVMHost(context)
fixed

2022-06-22 08:43 UTC, sasurobert submitted a review, later dismissed

2022-06-28 10:21 UTC, matei-p commented on arwen/contexts/async.go
> +		context.callbackParentCall = stackContext.(*asyncContext).
We need it. Certain scenarios will fail otherwise

2022-06-28 10:28 UTC, sasurobert commented on arwen/contexts/async.go
> +		context.callbackParentCall = stackContext.(*asyncContext).
smae for line 1006 - should work without any type assertion.

2022-06-28 12:13 UTC, sasurobert approved these changes

2022-06-28 13:27 UTC, sasurobert approved these changes

2022-06-28 13:27 UTC, merged