Fixes warm instance
ElrondNetwork/wasm-vm pull request #609
Opened 2022-09-14 13:00 UTC by ovstinga

2022-09-20 14:21 UTC, ovstinga commented
TODO: 

- [ ] add fuzzy test from another branch (already created)
- [ ] profile again with different values to check for any memory leaks (just to be extra sure...)
- [ ] small cleanup (refactor)

2022-09-21 07:49 UTC, sasurobert commented on arwen/contexts/blockchain_test.go
> +	"github.com/ElrondNetwork/wasm-vm/crypto/hashing"
goimports

2022-09-21 07:49 UTC, sasurobert commented on arwen/contexts/runtime.go
> +	//fmt.Println("byteCodeUsed")
delete

2022-09-21 07:49 UTC, sasurobert commented on arwen/contexts/runtime.go
> +func (context *runtimeContext) ShallowClean() {
add comment to unexported function.

2022-09-21 07:49 UTC, sasurobert commented on mock/context/instanceMock.go
> +func (instance *InstanceMock) ShallowCopy() wasmer.InstanceHandler {
comment on public functions

2022-09-21 07:49 UTC, sasurobert commented on mock/context/instanceMock.go
> +func (instance *InstanceMock) ShallowClean() {
comment on public functions

2022-09-21 07:49 UTC, sasurobert commented on mock/world/worldAccountMap.go
> +	"github.com/ElrondNetwork/wasm-vm/crypto/hashing"
goimports

2022-09-21 07:49 UTC, sasurobert commented on wasmer/instance.go
> +func (instance *Instance) ShallowClean() {
add comment to public function

2022-09-21 07:49 UTC, sasurobert commented on wasmer/instance.go
> +
add comment to public function

2022-10-07 17:09 UTC, andrei-marinica requested changes

2022-10-10 14:17 UTC, andrei-marinica approved these changes

2022-10-11 07:44 UTC, sasurobert approved these changes

2022-10-11 07:45 UTC, merged